<a href="https://colab.research.google.com/github/kasidejcha/jobsdb_data_scrape/blob/main/run_data_scrape_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/kasidejcha/jobsdb_data_scrape.git scrape

Cloning into 'scrape'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 21 (delta 6), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (21/21), done.

In [2]:
from scrape import jobsdb_data_scrape

jobsdb_data_scrape.run_jobsdb_scape()

Scrape Page Number(1-3): 1
Filter unwanted position: Senior
Filtering out: ['Senior']

Company Name: True Digital Group Co., Ltd.
Position: Junior Data Scientist
Location: Huaykwang
Requirement:
•  Transform raw data to actionable business insights
•  Select, configure & implement analytics solutions
•  Develop job ETL
Link:  https://th.jobsdb.com/th/en/job/job-300003002339652?token=0~9d545f47-4919-4fe1-99c8-ce3c54a3426c&sectionRank=1&jobId=jobsdb-th-job-300003002339652
Date Posted:  2021-03-31


Company Name: Tongthai Information and Technology Co., Ltd.
Position: Data Analyst  (เจ้าหน้าที่วิเคราะห์ข้อมูล)
Location: Huaykwang
Requirement not found
Link:  https://th.jobsdb.com/th/en/job/job-300003002335991?token=0~9d545f47-4919-4fe1-99c8-ce3c54a3426c&sectionRank=2&jobId=jobsdb-th-job-300003002335991
Date Posted:  2021-03-31


Company Name: TD Tawandang Co., Ltd.
Position: Data Scientist
Location: Bangrak
Requirement:
•  Data Scientist
•  Retail Business
•  Near BTS Chong Nonsi
Link:  https://th.jobsdb.com/th/en/job/job-300003002335896?token=0~9d545f47-4919-4fe1-99c8-ce3c54a3426c&sectionRank=3&jobId=jobsdb-th-job-300003002335896
Date Posted:  2021-03-31


Company Name: SKOOTAR BEYOND CO., LTD.
Position: Data Analyst - MySQL
Location: Wattana
Requirement:
•  Data Analyst Business Intelligence แอปขนส่งออนไลน์
•  ประสบการณ์ 2ปี+ วิเคราะห์ฐานข้อมูล MySQL, Excel
•  เงินเดือน 25,000 - 40,000 ตามประสบการณ์
Link:  https://th.jobsdb.com/th/en/job/job-300003002339256?token=0~9d545f47-4919-4fe1-99c8-ce3c54a3426c&sectionRank=4&jobId=jobsdb-th-job-300003002339256
Date Posted:  2021-03-31


Company Name: TCP Group
Position: Data Analyst
Location: Bangbon
Requirement:
•  Solid experience as Data Analyst/Business Analyst
•  Strong analytical skills
•  High level managing large scale database
Link:  https://th.jobsdb.com/th/en/job/job-300003002334861?token=0~9d545f47-4919-4fe1-99c8-ce3c54a3426c&sectionRank=5&jobId=jobsdb-th-job-300003002334861
Date Posted:  2021-03-30


Company Name: Central Group (Corporate Units)
Position: Data Analysis
Location: Bangrak
Requirement:
•  data analysis
•  Business Performance
•  Business process improvement
Link:  https://th.jobsdb.com/th/en/job/job-300003002339496?token=0~9d545f47-4919-4fe1-99c8-ce3c54a3426c&sectionRank=6&jobId=jobsdb-th-job-300003002339496
Date Posted:  2021-03-31


Company Name: V-smart Co., Ltd.
Position: Syste Analyst (Data Warehouse)
Location: Bangkok
Requirement:
•  Five-day workweek
•  Free Lunch
•  Near Ramkhamhaeng airport rail link station
Link:  https://th.jobsdb.com/th/en/job/job-300003002343271?token=0~9d545f47-4919-4fe1-99c8-ce3c54a3426c&sectionRank=8&jobId=jobsdb-th-job-300003002343271
Date Posted:  2021-03-31


Company Name: Aetna Health Insurance (Thailand) Public Company Limited
Position: Lead Data Scientist
Location: Bangrak
Requirement:
•  Statistical analysis, predictive modeling
•  Directly report to CEO
•  Fluent in English both Spoken and Written
Link:  https://th.jobsdb.com/th/en/job/job-300003002335471?token=0~9d545f47-4919-4fe1-99c8-ce3c54a3426c&sectionRank=9&jobId=jobsdb-th-job-300003002335471
Date Posted:  2021-03-31


Company Name: THAI UNION GROUP PCL.
Position: Data Scientist
Location: Phayathai
Requirement:
•  Statistical Inference and Machine Learning
•  Data-Mining Techniques
•  Good Comman in English Skills, Near BTS area
Link:  https://th.jobsdb.com/th/en/job/job-300003002339169?token=0~9d545f47-4919-4fe1-99c8-ce3c54a3426c&sectionRank=10&jobId=jobsdb-th-job-300003002339169
Date Posted:  2021-03-31


Company Name: Infosearch Co., Ltd.
Position: Data visualizer (BI Support)
Location: Bangrak
Requirement:
•  Degree holder in Information Technology
•  1 years’ experience in BI or data visualization
•  Proficiency in data preparation,analysis
Link:  https://th.jobsdb.com/th/en/job/job-300003002330431?token=0~9d545f47-4919-4fe1-99c8-ce3c54a3426c&sectionRank=12&jobId=jobsdb-th-job-300003002330431
Date Posted:  2021-03-31


Company Name: Central Retail Corporation Ltd. (JD Finance)
Position: Junior Data Engineer
Location: Pathumwan
Requirement:
•  Understanding of Hadoop ecosystem
•  Experience with data pipeline and workflow
•  Familiar with APIs, JSON, REST
Link:  https://th.jobsdb.com/th/en/job/job-300003002342637?token=0~9d545f47-4919-4fe1-99c8-ce3c54a3426c&sectionRank=13&jobId=jobsdb-th-job-300003002342637
Date Posted:  2021-03-30


Company Name: KASIKORNBANK PUBLIC COMPANY LIMITED
Position: DATA & ANALYTICS CAREER DAY วันเสาร์ที่ 8 พ.ค. 64
Location: Bangkok
Requirement:
•  Data & Analytics Career Day
•  สอบข้อเขียนและสัมภาษณ์ในวันเดียว
•  วันเสาร์ที่ 8 พฤษภาคม 2564
Link:  https://th.jobsdb.com/th/en/job/job-300003002343089?token=0~9d545f47-4919-4fe1-99c8-ce3c54a3426c&sectionRank=15&jobId=jobsdb-th-job-300003002343089
Date Posted:  2021-03-31


Company Name: TD Tawandang Co., Ltd.
Position: Data Analytics
Location: Bangrak
Requirement:
•  Data Analysis
•  Retail / FMCG
•  Tableau & SQL Command
Link:  https://th.jobsdb.com/th/en/job/job-300003002334651?token=0~9d545f47-4919-4fe1-99c8-ce3c54a3426c&sectionRank=16&jobId=jobsdb-th-job-300003002334651
Date Posted:  2021-03-30


Company Name: Krungsri Bank (Bank of Ayudhya PCL.)
Position: Data Analytics Product Owner
Location: Yannawa
Requirement:
•  Exp. in customer journey, collaboration b/w IT, BU
•  Experience in manage analytics projects
•  Data through identifying,capturing,integrating
Link:  https://th.jobsdb.com/th/en/job/job-300003002335481?token=0~9d545f47-4919-4fe1-99c8-ce3c54a3426c&sectionRank=17&jobId=jobsdb-th-job-300003002335481
Date Posted:  2021-03-31


Company Name: dtac
Position: Manager, Data Analytics
Location: Pathumwan
Requirement:
•  data analyst or business data analyst
•  data modelling and segmentation projects
•  data models, database design development
Link:  https://th.jobsdb.com/th/en/job/job-300003002342718?token=0~9d545f47-4919-4fe1-99c8-ce3c54a3426c&sectionRank=18&jobId=jobsdb-th-job-300003002342718
Date Posted:  2021-03-30


Company Name: Locus Telecommunication Inc., Ltd.
Position: Data Scientist
Location: Huaykwang
Requirement:
•  data analytic, data science, data mining
•  Simulation and Statistics will be advantageous.
•  CW Tower, Rachada, Near MRT
Link:  https://th.jobsdb.com/th/en/job/job-300003002338876?token=0~9d545f47-4919-4fe1-99c8-ce3c54a3426c&sectionRank=20&jobId=jobsdb-th-job-300003002338876
Date Posted:  2021-03-30


Company Name: Krungsri Bank (Bank of Ayudhya PCL.)
Position: Data Strategist (VP)
Location: Yannawa
Requirement:
•  Enterprise data strategy, analytics roadmap
•  Experience in analytics operating model
•  Exp in execution on data-driven transformation
Link:  https://th.jobsdb.com/th/en/job/job-300003002334948?token=0~9d545f47-4919-4fe1-99c8-ce3c54a3426c&sectionRank=21&jobId=jobsdb-th-job-300003002334948
Date Posted:  2021-03-30


Company Name: FWD Life Public Company Limited
Position: Data Engineer (Platform)
Location: Bangkok
Requirement:
•  Managing Data Lake platform and services
•  More than 3 years Experience in ETL, Hadoop tech
•  Proven experience in Python, Kerberos, Linux & SQL
Link:  https://th.jobsdb.com/th/en/job/job-300003002347166?token=0~9d545f47-4919-4fe1-99c8-ce3c54a3426c&sectionRank=22&jobId=jobsdb-th-job-300003002347166
Date Posted:  2021-04-01


Company Name: Adecco Recruitment (Thailand) Limited
Position: Lead Data Scientist
Location: Bangkok
Requirement:
•  algorithms and statistical predictive models
•  reporting tools
•  analyses of structured and unstructured data
Link:  https://th.jobsdb.com/th/en/job/job-300003002345989?token=0~9d545f47-4919-4fe1-99c8-ce3c54a3426c&sectionRank=23&jobId=jobsdb-th-job-300003002345989
Date Posted:  2021-03-31


Company Name: Krungsri Bank (Bank of Ayudhya PCL.)
Position: Data PM/PMO
Location: Yannawa
Requirement:
•  Data Project Management Experiences
•  Manage Analytical Project using SDLC & Agile
•  Data-Driven and Growth Mindsets
Link:  https://th.jobsdb.com/th/en/job/job-300003002334934?token=0~9d545f47-4919-4fe1-99c8-ce3c54a3426c&sectionRank=24&jobId=jobsdb-th-job-300003002334934
Date Posted:  2021-03-30


Company Name: TCP Group
Position: Data Manager
Location: Bangbon
Requirement:
•  Formulate techniques for quality data collection
•  data handling and analysis
•  Develop data collection methods
Link:  https://th.jobsdb.com/th/en/job/job-300003002345741?token=0~9d545f47-4919-4fe1-99c8-ce3c54a3426c&sectionRank=25&jobId=jobsdb-th-job-300003002345741
Date Posted:  2021-03-30


Company Name: UTAC Thai Limited
Position: Data Analyst (Customer Service Team)/ BTS Bearing
Location: Bangna
Requirement:
•  at least 1 years working experiences
•  Technical Skill such as Java, Python, R, Tableau
•  Experiences in Hadoop, PySpark, Hive, Scala, Kafka
Link:  https://th.jobsdb.com/th/en/job/job-300003002335401?token=0~9d545f47-4919-4fe1-99c8-ce3c54a3426c&sectionRank=27&jobId=jobsdb-th-job-300003002335401
Date Posted:  2021-03-31


Company Name: KASIKORNBANK PUBLIC COMPANY LIMITED
Position: Enterprise Risk Management and Data Analytics (Head Office Ratburana)
Location: Ratburana
Requirement:
•  Data Analytics
•  Risk Management
•  Big Data
Link:  https://th.jobsdb.com/th/en/job/job-300003002346991?token=0~9d545f47-4919-4fe1-99c8-ce3c54a3426c&sectionRank=29&jobId=jobsdb-th-job-300003002346991
Date Posted:  2021-04-01


Company Name: Frasers Property (Thailand) Public Co., Ltd. (FPT)
Position: IT Data Analyst
Location: Pathumwan
Requirement:
•  Bachelor or Master’s degree in Quantitative fields
•  0 - 3 years  in data science, data analytics
•  Advanced statistics, Data science
Link:  https://th.jobsdb.com/th/en/job/job-300003002339292?token=0~9d545f47-4919-4fe1-99c8-ce3c54a3426c&sectionRank=30&jobId=jobsdb-th-job-300003002339292
Date Posted:  2021-03-31